### PR TITLE
Add more databases options

### PR DESCRIPTION
**Pull request by mike325**
Hey guys I like your docker image and I think it would just better if it would be able to use an external mysql database. Please let me know your thoughts about it!.

### CODE REVIEW

**Comment by kilpatty** [comment]
Thanks for the contribution! Give me a little while to look over it, and make sure everything is working well - Then I'll accept!

**Comment by w0rldart** [comment]
But surely, if you intend to support for other ways of handling data storage, you'd not just for MySQL, but PostgreSQL as well, no?

**Comment by mike325** [comment]
Ghost is planning to drop the PostgreSQL support in the release 1.0.0 due to a lot of compatibility problems between MySQL (and SQLite) and PostgreSQL, so I thought it would be better to have just the databases that will keep the support.

**Comment by kilpatty** [comment]
Sorry for the delay! I'll have this checked out, and merged tonight pending no issues!

**Pull request closed without merging**
