### PR TITLE
update ghost to 0.9.0

### LINKED ISSUE #3: Upgrade to 0.9.0
Ghost has released [v0.9.0](https://github.com/TryGhost/Ghost/releases/tag/0.9.0)

### PR DESCRIPTION
**Pull request by blockloop**
Fix #3

### CODE REVIEW

**Comment by killianbrackey** [comment]
Thanks for the help @blockloop!

**Comment by blockloop** [comment]
@killianbrackey does CI push to docker hub? I saw that Travis build completed but didn't see anything about pushing the image in the .travis.yml file.

**Comment by kilpatty** [comment]
It will automatically push on a retag, working on that now!

**Comment by kilpatty** [comment]
@blockloop It is building on docker hub now :)

**Comment by blockloop** [comment]
If only there were more 1 char PRs...

**Pull request merged**
